document.write("<h2>Javascript new Dtae</h2>");
var d=new Date();
document.write(d);
document.write("<br/>");
document.write("Date :"+d.getDate());
document.write("<br/>");
document.write("Day :"+d.getDay());
document.write("<br/>");
document.write("Year :"+d.getFullYear());
document.write("<br/>");
document.write("Hours :"+d.getHours());
document.write("<br/>");
document.write("minutes : "+d.getMinutes());
document.write("<br/>");
document.write("Seconds : "+d.getSeconds());
